---
name: Call Trivy
on:
 push:
   branches: [main]
 pull_request:
jobs:
 scan:
   name: Scan
   uses: course-testing-org/actions/.github/workflows/reusable-trivy.yml@aerinkayne-patch-1
   with:
    image: 'ghcr.io/course-testing-org/wordsmith-web:latest'
