---
name: Call Trivy
on:
 workflow_dispatch:
jobs:
 scan:
   name: Scan
   uses: course-testing-org/actions/.github/workflows/reusable-trivy.yml@main
   with:
    image: 'ghcr.io/course-testing-org/wordsmith-web:latest'
